kloudlite/api

apps/infra/internal/app/graph/schema.resolvers.go
apps/infra/internal/domain/clusters.go
apps/infra/internal/domain/domain.go
pkg/k8s/client.go

- cluster status updates are now fetched from k8s api, instead of resource-watcher
- cluster deletion is now done in 2 steps: + on delete request, k8s cluster resource is deleted, and it goes into its finalizing phase + and, while listing or getting the resource, we check if resource is deleted, and it if it is, then that result is omitted

feat(infra): fixes cluster status updates, and deletions

---

apps/infra/internal/domain/clusters.go
apps/infra/internal/domain/nodepool.go

fixes, update for nodepool and cluster resources
- earlier, graphql update to nodepool and cluster resources were overriding the entire spec for the resources, which resulted in data loss and in failed reconcilations for those resources

feat(infra): fixes update for nodepool and cluster resources

---

apps/infra/internal/app/app.go
apps/infra/internal/app/process-error-on-apply.go
apps/infra/internal/app/process-resource-updates.go

- makes infra error-on-apply tap on the same topic as console:error-on-apply, as message office currently dispatched onto it only. MIGHT FIX in future releases
- corrects infra resource updates subscription topic

feat(apps/infra): fixes infra resource updates, and error-on-apply

---

.tools/nvim/__http__/console/apps.graphql.yml
.tools/nvim/__http__/console/environments.graphql.yml
apps/console/internal/domain/domain.go
apps/console/internal/domain/environment.go
apps/console/internal/domain/project.go
apps/message-office/internal/app/app.go

- fixes, incorrect key for project cluster KV cache, it needed to have key composed of `accountName` and `projectName`, but we had it set to `projectName` only, which was a BIG mistake

fix(console): project cluster KV cache

---

flake.lock
go.mod
go.sum

- bumps go from `v1.21.4` to `v1.21.5`
- also updates `github.com/kloudlite/operator` to latest `release-1.0.5`

chore: bumps go version to v1.21.5

---

apps/auth/Containerfile.local
apps/auth/internal/app/github.go
apps/auth/internal/app/gitlab.go
apps/auth/internal/app/google.go
apps/auth/internal/app/graph/schema.resolvers.go
apps/infra/internal/domain/clusters.go

- instead, they now just return an empty string, and logs the error

fix(apps/auth): disabled oauth2 providers, does not throw an error now

---

.tools/nvim/__http__/auth/auth.graphql.yml
.tools/nvim/__http__/console/environments.graphql.yml
apps/console/internal/app/graph/schema.resolvers.go
apps/console/internal/domain/api.go
apps/console/internal/domain/app.go
apps/console/internal/domain/config.go
apps/console/internal/domain/environment.go
apps/console/internal/domain/mres.go
apps/console/internal/domain/router.go
apps/console/internal/domain/secret.go
apps/console/internal/domain/vpn-device.go

- fixes environment cloning
- refactors other domain items `app`, `config`, `secret` etc. to assist in environment cloning

refactor(apps/console): refactors environment cloning

---

apps/console/internal/domain/environment.go
apps/console/internal/domain/project-managed-service.go
apps/console/internal/domain/project.go

updated target namespace to md5 hash namespace for below resource:
- Project
- Environment
- Project Manage Service

fix(console): updated target namespace to md5 hash namespace

---

.tools/nvim/__http__/console/logs-and-metrics.rest.yml
.tools/nvim/__http__/infra/vpn-devices.graphql.yml
apps/console/internal/app/app.go
apps/console/internal/app/observability-handler.go
apps/iam/internal/app/grpc-server.go
apps/iam/internal/entities/role-binding.go
apps/iam/types/types.go
apps/infra/internal/env/env.go

Fix/iam account member role bindings, and resource metrics

---

.tools/nvim/__http__/console/logs-and-metrics.rest.yml
.tools/nvim/__http__/infra/vpn-devices.graphql.yml
CHANGELOG.md
apps/console/internal/app/app.go
apps/console/internal/app/observability-handler.go
apps/console/internal/domain/environment.go
apps/console/internal/domain/mres.go
apps/console/internal/domain/vpn-device.go
apps/iam/internal/app/grpc-server.go
apps/iam/internal/entities/role-binding.go
apps/iam/types/types.go
apps/infra/internal/app/graph/generated/generated.go
apps/infra/internal/app/graph/schema.graphqls
apps/infra/internal/app/graph/schema.resolvers.go
apps/infra/internal/domain/api.go
apps/infra/internal/domain/clusters.go
apps/infra/internal/domain/pv.go
apps/infra/internal/env/env.go
apps/websocket-server/internal/domain/logs.go

Release v1.0.1

---

apps/console/internal/app/adapter-resource-update-publish.go
apps/console/internal/domain/api.go
apps/console/internal/domain/environment.go
apps/console/internal/domain/project-managed-service.go
apps/console/internal/domain/vpn-device.go

KLO-106: fix(console) Add environment name while publishing nats event for environment resources

---

apps/infra/internal/domain/domain-entries.go
apps/infra/internal/domain/helm-release.go
apps/infra/internal/domain/ingress.go

Add clustername in nats event publishing for below resources:
- helm release
- domain entry (via Ingress resource)

fix(infra): Add clustername in nats event publishing

---

apps/console/internal/app/graph/schema.resolvers.go
apps/infra/internal/app/graph/schema.resolvers.go

change error return type in schema resolver

fix(console/infra): fixes returnning nil instead of err typo

---

apps/container-registry/internal/app/adapter-github.go
apps/container-registry/internal/app/graph/schema.graphqls

Resolves kloudlite/kloudlite#47

[KLO-159] feat(container-registry): now also lists forks in search repos API

---

apps/console/internal/app/graph/generated/generated.go
apps/console/internal/app/graph/model/models_gen.go
apps/console/internal/app/graph/schema.resolvers.go
apps/console/internal/app/graph/struct-to-graphql/common-types.graphqls
apps/console/internal/domain/mres.go
apps/console/internal/domain/project-managed-service.go
apps/console/internal/entities/secret.go
apps/infra/internal/app/graph/generated/generated.go
apps/infra/internal/app/graph/model/models_gen.go
apps/infra/internal/app/graph/schema.resolvers.go
apps/infra/internal/app/graph/struct-to-graphql/common-types.graphqls
apps/infra/internal/entities/cluster-managed-service.go
apps/infra/internal/entities/field-constants/generated_constants.go
apps/infra/internal/entities/msvc-template.go
go.mod
go.sum

- nodeselector and tolerations for app and managed services
- managed resource secrets are now stored in our database as `readOnly` secrets

fix: nodeselector and tolerations for managed services, and managed

---

apps/console/internal/app/graph/common-types.resolvers.go
apps/console/internal/app/graph/secret.resolvers.go
apps/infra/internal/app/graph/schema.resolvers.go

Updated k8s-schema and gql, because of types changes on operator.

:art: Updated gql and k8s-schema in infra and console

---

apps/container-registry/internal/app/adapter-github.go
apps/container-registry/internal/app/git-webhook-consumer.go
apps/container-registry/internal/domain/build.go

- implemented build trigger query.

:sparkles: Added build trigger option

---

apps/console/internal/domain/app.go
apps/container-registry/internal/app/adapter-resource-update-publish.go
apps/container-registry/internal/app/git-webhook-consumer.go
apps/container-registry/internal/app/graph/buildrun.resolvers.go
apps/container-registry/internal/app/process-resource-updates.go
apps/container-registry/internal/domain/api.go
apps/container-registry/internal/domain/build-run.go
apps/container-registry/internal/domain/build.go
apps/container-registry/internal/domain/entities/build-run.go

- updated syncstatus for buildrun [ needs to test ]
- added option for build trigger

:zap: Updated build run syncstatus

---

apps/container-registry/internal/domain/build-run.go
apps/websocket-server/internal/domain/logs.go
apps/websocket-server/internal/domain/logs/main.go

- fixed issue with the record version in websocket server.
- removed record version parsing in registry as not needed for now.

:bug: Fixed issue with record version

---

.tools/nvim/__http__/auth/invite-code.graphql.yml
apps/auth/internal/app/app.go
apps/auth/internal/app/graph/functions.go
apps/auth/internal/app/graph/generated/generated.go
apps/auth/internal/app/graph/model/models_gen.go
apps/auth/internal/app/graph/schema.graphqls
apps/auth/internal/app/graph/schema.resolvers.go
apps/auth/internal/domain/domain.go
apps/auth/internal/domain/impl.go
apps/auth/internal/domain/invite-code.go
apps/auth/internal/entities/entities.go
go.sum

Resolves kloudlite/kloudlite#221

API: Invite code implementation

---

apps/comms/internal/app/graph/generated/generated.go
apps/comms/internal/app/graph/schema.graphqls
apps/comms/internal/app/graph/schema.resolvers.go
apps/comms/internal/domain/api.go
apps/comms/internal/domain/notification.go
apps/comms/internal/env/env.go
apps/comms/internal/framework/framework.go
apps/gateway/supergraph.yml

- fixed minor issues in comms for notification and alerts.

:art: Fixed minor issue in comms for notification and alert

---

apps/console/internal/domain/environment.go
apps/infra/internal/entities/field-constants/generated_constants.go

Resolves kloudlite/kloudlite#248

fix: migrating environment cache from kv, back to db

---

apps/accounts/internal/domain/accounts.go
apps/console/internal/domain/environment.go

- added deleting resources of environment while deleting environment.

350 all resource cleanups should happen properly when environment is getting deleted it is not deleting all the resources under it

---

apps/console/internal/domain/app.go

Resolves kloudlite/kloudlite#276

fix: updates apps on cluster, when removing all device intercepts

---

apps/kube-health/.gitignore
apps/kube-health/Dockerfile
apps/kube-health/Taskfile.yml
apps/kube-health/main.go

- added api for kubernetes resources health check

:sparkles: Added api for kubernetes resource health check
